spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
            routes:
              - id: product-catalog
                uri: http://localhost:8081
                predicates:
                  - Path=/product/**
              - id: shopping-cart
                uri: http://localhost:8082
                predicates:
                  - Path=/cart/**